image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - make build
  artifacts:
    paths:
      - dps
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - ./dps
